site_name: Python Software Foundation Policies
theme:
  name: material
  custom_dir: ./overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
plugins:
  - git-revision-date-localized:
      type: date
      enable_creation_date: false
      fallback_to_build_date: true
extra:
  homepage: https://python.org/psf/
  preview: !ENV [PREVIEW, "False"]
site_url: https://policies.python.org/
repo_url: https://github.com/psf/policies

nav:
  - "PSF-Privacy-Notice.md"
  - "pypi.org":
      - "pypi.org/Acceptable-Use-Policy.md"
      - "pypi.org/Code-of-Conduct.md"
      - "pypi.org/Terms-of-Use.md"
      - "pypi.org/Privacy-Notice.md"
  - "python.org":
      - "python.org/CVE-Numbering-Authority.md"
      - "python.org/Contributing.md"
      - "python.org/Copyright-Policy.md"
      - "python.org/Legal-Statements.md"
      - "python.org/Privacy-Notice.md"
      - "Code of Conduct":
          - "python.org/code-of-conduct/index.md"
          - "python.org/code-of-conduct/Best-Practices.md"
          - "python.org/code-of-conduct/Enforcement-Procedures.md"
          - "python.org/code-of-conduct/Procedures-for-Reporting-Incidents.md"
          - "python.org/code-of-conduct/Transparency-Report-Guidelines.md"
  - "us.pycon.org":
      - "us.pycon.org/Privacy-Notice.md"
      - "Code of Conduct":
          - "us.pycon.org/code-of-conduct/index.md"
          - "us.pycon.org/code-of-conduct/Enforcement-Procedures.md"
          - "us.pycon.org/code-of-conduct/Procedures-for-Reporting-Incidents.md"
